[tool.poetry]
name = "llm-agent-memory-letta"
version = "0.1.0"
description = ""
authors = ["JP <jonpaulboyd@hotmail.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"
python-dotenv = "1.0.1"
openai = "1.45.1"
letta = "0.1.4"
crewai-tools = "0.12.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
